Repository DeveloperAcademy-POSTECH/2025-C4-M11-NLP, pull requests merged in 2025-07, with the labels that each got.

#3 [docs] README.md 기간 설정
  README.md
Labels: documentation

#5 🍀 ETC: #2 Tuist 초기설정 진행, .gitIgnore 추가
  NLP/.gitignore
  NLP/NLP/Sources/NLPApp.swift
  NLP/NLP/Tests/NLPTests.swift
  NLP/Project.swift
  NLP/Tuist.swift
  NLP/Tuist/Package.resolved
  NLP/Tuist/Package.swift
  NLP/mise.toml
Labels: enhancement

#27 ✨ Feat: #19 Stage 1 손전등 발견 및 조명 변경 구현
  NLP/NLP/Resources/Assets.xcassets/Flashlight.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/Flashlight.imageset/flashlight.png
  NLP/NLP/Resources/Assets.xcassets/NoLight.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/NoLight.imageset/no_light.png
  NLP/NLP/Resources/Assets.xcassets/TurnOnFlashLight.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/TurnOnFlashLight.imageset/turn_on_flashlight.png
  NLP/NLP/Resources/GameTileSet.sks
  NLP/NLP/Resources/MainGameScene.sks
  NLP/NLP/Resources/StageOneGameScene.sks
  NLP/NLP/Sources/Game/Enum/PhysicsCategory.swift
  NLP/NLP/Sources/Game/Sprites/FlashlightSprite.swift
  NLP/NLP/Sources/Game/Sprites/NoLightSprite.swift
  NLP/NLP/Sources/Game/Sprites/PlayerSprite.swift
  NLP/NLP/Sources/Game/Sprites/TurnOnFlashlightSprite.swift
  NLP/NLP/Sources/Game/StageOneGameScene/StageOneGameScene.swift
  NLP/NLP/Sources/Presentation/MainGameScene/MainGameState.swift
  NLP/NLP/Sources/Presentation/MainGameScene/MainGameView.swift
  NLP/NLP/Sources/Presentation/RootScene/RootView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameViewModel.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/DialogView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/PauseView.swift
Labels: enhancement, 💻Air

#33 Fix: 조명 Sprite 표현 오류 수정
  NLP/NLP/Resources/StageOneGameScene.sks
Labels: bug, 💻Air

#36 ✨ Feat: Stage 1 EP1 Dialog 구현
  NLP/NLP/Resources/StageOneGameScene.sks
  NLP/NLP/Sources/Game/Enum/StageOneMonologuePhase.swift
  NLP/NLP/Sources/Game/StageOneGameScene/StageOneGameScene.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameViewModel.swift
  NLP/NLP/Sources/Utils/Constants/ConstantPositions.swift
Labels: enhancement, 💻Air

#48 ✨ Feature: #20 Stage1 FlashLight 발견, note 발견 구현
  NLP/NLP/Resources/Assets.xcassets/note.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/note.imageset/note.png
  NLP/NLP/Resources/StageOneGameScene.sks
  NLP/NLP/Sources/Game/Enum/PhysicsCategory.swift
  NLP/NLP/Sources/Game/Enum/StageOneMonologuePhase.swift
  NLP/NLP/Sources/Game/Sprites/NoteSprite.swift
  NLP/NLP/Sources/Game/Sprites/PlayerSprite.swift
  NLP/NLP/Sources/Game/StageOneGameScene/StageOneGameScene.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameViewModel.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/LightInfoView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/NoteInfoView.swift
  NLP/NLP/Sources/Utils/Constants/GameItems.swift
Labels: 🇺🇸Wonjun

#55 ✨ Feat: #37 Stage 1 EP1 중앙통제실 비밀번호 창 구현
  NLP/NLP/Resources/Assets.xcassets/door_closed.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/door_closed.imageset/door_closed.png
  NLP/NLP/Resources/Assets.xcassets/door_opened.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/door_opened.imageset/door_opened.png
  NLP/NLP/Resources/Assets.xcassets/number_button_0.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_0.imageset/number_button_0.png
  NLP/NLP/Resources/Assets.xcassets/number_button_1.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_1.imageset/number_button_1.png
  NLP/NLP/Resources/Assets.xcassets/number_button_2.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_2.imageset/number_button_2.png
  NLP/NLP/Resources/Assets.xcassets/number_button_3.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_3.imageset/number_button_3.png
  NLP/NLP/Resources/Assets.xcassets/number_button_4.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_4.imageset/number_button_4.png
  NLP/NLP/Resources/Assets.xcassets/number_button_5.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_5.imageset/number_button_5.png
  NLP/NLP/Resources/Assets.xcassets/number_button_6.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_6.imageset/number_button_6.png
  NLP/NLP/Resources/Assets.xcassets/number_button_7.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_7.imageset/number_button_7.png
  NLP/NLP/Resources/Assets.xcassets/number_button_8.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_8.imageset/number_button_8.png
  NLP/NLP/Resources/Assets.xcassets/number_button_9.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_9.imageset/number_button_9.png
  NLP/NLP/Resources/Assets.xcassets/number_button_check.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_check.imageset/number_button_check.png
  NLP/NLP/Resources/Assets.xcassets/number_button_del.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_del.imageset/number_button_del.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_0.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_0.imageset/number_button_pushed_0.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_1.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_1.imageset/number_button_pushed_1.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_2.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_2.imageset/number_button_pushed_2.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_3.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_3.imageset/number_button_pushed_3.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_4.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_4.imageset/number_button_pushed_4.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_5.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_5.imageset/number_button_pushed_5.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_6.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_6.imageset/number_button_pushed_6.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_7.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_7.imageset/number_button_pushed_7.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_8.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_8.imageset/number_button_pushed_8.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_9.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_9.imageset/number_button_pushed_9.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_check.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_check.imageset/number_button_pushed_check.png
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_del.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/number_button_pushed_del.imageset/number_button_pushed_del.png
  NLP/NLP/Sources/Game/Enum/PasswordKeypadValue.swift
  NLP/NLP/Sources/Game/Enum/StageOneMonologuePhase.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameViewModel.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/PasswordButtonView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/PasswordFieldView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/PasswordView.swift
  NLP/NLP/Sources/Utils/Constants/ConstantPasswordResult.swift
Labels: enhancement, 💻Air

#77 fix: 조이스틱 크래시 버그 수정
  NLP/NLP/Sources/Game/GameScene/GameScene.swift
  NLP/NLP/Sources/Game/Shapes/JoyStick.swift
Labels: 👊🏻GO

#84 ✨ Feat: #61 Stage 1 완료 후 중간스토리로 이동 구현
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameView.swift
Labels: enhancement, 💻Air

#98 🎨 Design: #97 아이템 정보 화면 디자인 개선
  NLP/NLP/Resources/Assets.xcassets/itemBackGround.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/itemBackGround.imageset/배경 테두리.png
  NLP/NLP/Sources/Common/DesignSystem/DialogBackgroundView.swift
  NLP/NLP/Sources/Common/DesignSystem/ItemBackGround.swift
  NLP/NLP/Sources/Common/DesignSystem/UserDialogInputField.swift
  NLP/NLP/Sources/Common/DesignSystem/XButton.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/LightInfoView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/NoteInfoView.swift
  NLP/NLP/Sources/Presentation/StageTwoScene/SubView/ItemCollectionView.swift
Labels: 🇺🇸Wonjun

#115 ✨ Feat: #102 Stage 3 ep5 View 구현 (SKScene 제외)
  NLP/NLP/Sources/App/CoordinatorPath.swift
  NLP/NLP/Sources/Game/Enum/StageThreeMonologuePhase.swift
  NLP/NLP/Sources/Game/StageThreeGameScene/StageThreeGameScene.swift
  NLP/NLP/Sources/Presentation/RootScene/RootView.swift
  NLP/NLP/Sources/Presentation/StageThreeScene/StageThreeView.swift
  NLP/NLP/Sources/Presentation/StageThreeScene/StageThreeViewModel.swift
  NLP/NLP/Sources/Presentation/StartGameScene/StartGameViewModel.swift
  NLP/NLP/Sources/Utils/Constants/GameItems.swift
Labels: enhancement, 💻Air

#117 ✨Feature: UX 고도화
  NLP/NLP/Resources/Assets.xcassets/Finn.imageset/Contents.json
  NLP/NLP/Sources/Common/CustomKeyboard/CustomKeyboardView.swift
  NLP/NLP/Sources/Common/DesignSystem/DialogView.swift
Labels: 👊🏻GO

#138 ✨ Feat: #137 산소 발생기 Tool 구현
  NLP/NLP/Resources/Assets.xcassets/Finn.imageset/Contents.json
  NLP/NLP/Sources/Common/CustomKeyboard/CustomKeyboardView.swift
  NLP/NLP/Sources/Common/MusicManager.swift
  NLP/NLP/Sources/Dialog/DialogManager.swift
  NLP/NLP/Sources/Dialog/Tool/OxygenTool.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/StageOneGameView.swift
  NLP/NLP/Sources/Utils/Constants/ConstantInstructions.swift
Labels: 🇺🇸Wonjun

#148 ✨ Feature: #146 Stage 3 4 중간스토리 구현 및 연결
  NLP/NLP/Sources/App/CoordinatorPath.swift
  NLP/NLP/Sources/Presentation/MiddleStoryScene/MiddleStoryView.swift
  NLP/NLP/Sources/Presentation/MiddleStoryScene/MiddleStoryViewModel.swift
  NLP/NLP/Sources/Presentation/RootScene/RootView.swift
  NLP/NLP/Sources/Presentation/StageThreeScene/StageThreeView.swift
  NLP/NLP/Sources/Utils/Constants/ConstantMiddleStory.swift
Labels: enhancement, 💻Air

#150 ✨ Feature: #149 Stage 3 수정
  NLP/NLP/Resources/StageThreeGameScene.sks
  NLP/NLP/Sources/Game/Enum/StageThreeMonologuePhase.swift
  NLP/NLP/Sources/Game/StageThreeGameScene/StageThreeGameScene.swift
  NLP/NLP/Sources/Presentation/StageThreeScene/StageThreeView.swift
  NLP/NLP/Sources/Utils/Constants/ConstantPositions.swift
Labels: enhancement, 💻Air

#154 ✨ Feature: #151 Stage 3 폭발 진동 효과 추가
  NLP/NLP/Sources/Common/GradientHaptic.swift
  NLP/NLP/Sources/Game/StageThreeGameScene/StageThreeGameScene.swift
  NLP/NLP/Sources/Presentation/StageThreeScene/StageThreeView.swift
Labels: enhancement, 💻Air

#171 ✨ Fix / Feature: #162 StreamingText 오류 해결 및 개선
  NLP/NLP/Sources/Common/DesignSystem/SignalMachineDetailView.swift
  NLP/NLP/Sources/Common/DesignSystem/StreamingText.swift
  NLP/NLP/Sources/Game/Enum/SignalMachinePhase.swift
Labels: enhancement, 💻Air

#180 🎨 Design #167 Dialogchatview UI 개선
  NLP/NLP/Resources/Assets.xcassets/end_negative.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/end_positive_1.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/jane.imageset/Contents.json
  NLP/NLP/Resources/Assets.xcassets/killerRobot.imageset/Contents.json
  NLP/NLP/Sources/Common/DesignSystem/DialogChatView.swift
Labels: 🇺🇸Wonjun

#189 Fix: 첫번째 StreamingText skip 동작 무시되는 에러 해결
  NLP/NLP/Sources/Common/DesignSystem/StreamingText.swift
Labels: bug, 💻Air

#190 ✨ Feat: #182 GameStoryView와 MiddleStoryView의 StreamingText에 frame 적용
  NLP/NLP/Sources/Presentation/MiddleStoryScene/MiddleStoryView.swift
  NLP/NLP/Sources/Presentation/StartGameScene/GameIntroView.swift
Labels: enhancement, 💻Air

#193 ✨ Feat: #191 디자인 시스템 추가 및 반영
  NLP/NLP/Sources/Common/DesignSystem/DialogChatView.swift
  NLP/NLP/Sources/Common/DesignSystem/DialogView.swift
  NLP/NLP/Sources/Common/DesignSystem/GameButton.swift
  NLP/NLP/Sources/Common/DesignSystem/MonologueView.swift
  NLP/NLP/Sources/Common/DesignSystem/NLPColor.swift
  NLP/NLP/Sources/Common/DesignSystem/NLPFont.swift
  NLP/NLP/Sources/Common/DesignSystem/OxygenGaugeView.swift
  NLP/NLP/Sources/Common/DesignSystem/SignalMachineDetailView.swift
  NLP/NLP/Sources/Common/DesignSystem/StreamingText.swift
  NLP/NLP/Sources/Game/Enum/SignalMachinePhase.swift
  NLP/NLP/Sources/Presentation/EndingCreditScene/EndingCreditView.swift
  NLP/NLP/Sources/Presentation/EndingCreditScene/SubView/CreditView.swift
  NLP/NLP/Sources/Presentation/MiddleStoryScene/MiddleStoryView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/ChatBotInstructionInputView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/ItemStreamingTextView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/PasswordFieldView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/PasswordView.swift
  NLP/NLP/Sources/Presentation/StageOneGameScene/SubView/PauseView.swift
  NLP/NLP/Sources/Presentation/StageOneIntroScene/SubView/IntroDialogEndView.swift
  NLP/NLP/Sources/Presentation/StageOneIntroScene/SubView/IntroDialogView.swift
  NLP/NLP/Sources/Presentation/StageTwoScene/SubView/ItemCollectionView.swift
  NLP/NLP/Sources/Presentation/StartGameScene/GameIntroView.swift
  NLP/NLP/Sources/Presentation/StartGameScene/GameStoryView.swift
  NLP/NLP/Sources/Presentation/StartGameScene/StartGameView.swift
Labels: enhancement, 💻Air

#206 ✨ Feat: #176 Monologue 프로토콜 수정 및 각 스테이지 Monologue Color 설정
  NLP/NLP/Sources/Common/DesignSystem/MonologueView.swift
  NLP/NLP/Sources/Game/Enum/MonologuePhase.swift
  NLP/NLP/Sources/Game/Enum/StageFourMonologuePhase.swift
  NLP/NLP/Sources/Game/Enum/StageOneMonologuePhase.swift
  NLP/NLP/Sources/Game/Enum/StageThreeMonologuePhase.swift
  NLP/NLP/Sources/Game/Enum/StageTwoMonologuePhase.swift
Labels: enhancement, 💻Air
